# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1fed3e0c9081e38ce603fbd6c06e4deb555893749e6495c282b41832eeda20170c80372303da63689fa173705bd861ab8952a2166c1ab16e02bfd11dff4f41a5

test:
  secret_key_base: ba75c6d0ac9933d0750f8c8fa6e0d7010bff492d4cb228af93769a74d54ec12c8f42ad0b41b7430c830ae9f74df063bdd65b3a30ee4f24766ba1cdd07e36e9a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
